### ISSUE TITLE
Grid doesn't work properly

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#31]
The grid seems to be static in the game window.

**Comment by ThomasGaubert** [comment]
High priority and should be fixed by next milestone.

**Comment by maximusvladimir** [comment]
Partially fixed, however, now the grid and entities are limited to a small portion of the world.

**Comment by maximusvladimir** [comment]
Broken again.

**Comment by maximusvladimir** [comment]
Fully operational.
