### ISSUE TITLE
Mouse stuff in Game.java, ChunkRenderer.java, etc should use a universal MouseHandler (like the KeyboardHandler)

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#40]
also listeners should be constants

**Comment by abauer** [comment]
working on it

**Comment by abauer** [comment]
just did keyboard listener; unfortunately focuslistener can't be a constant

**Comment by abauer** [comment]
fixed as of commit 8fad9a55d98718f915d20160bbaf35c80dd2998f

**Comment by maximusvladimir** [comment]
Technically, it is not fixed, but it has been partially implemented.
